export const baseUrl = process.env.REACT_APP_API_BASE_URL;
export const stripePublishableKey = "pk_test_51RcPdGGd8yfmOEEK0l9c8eBdLAQCkERmaTRWsk3t7lZAp49AcyYmyXmDld9pKp56eNIQGGJdFaeONkWnOxMHOqSy00c9Ji2AfQ"
